### ISSUE TITLE
Class 'InterestCollectionViewCell' has no initializers

### ISSUE THREAD

**Issue by Flum-X** [soapyigu/Swift-30-Projects#36]
道长，接触Swift时间不长，参考你的第十个项目Interests，
InterestCollectionViewCell文件一直报：Class 'InterestCollectionViewCell' has no initializers错误，网上查阅了一些资料始终没有解决，Xcode 9.4.1,Swift4.1

**Comment by soapyigu** [comment]
我查看了一下。应该没有问题，可能你是属性的惊叹号误删了之类。Xcode 10, Swift 4.2。

**Comment by Flum-X** [comment]
还真是[尴尬]，谢谢
